#! /bin/bash

install_packages() {
  sudo pacman -Syu
  packages=("zip" "hyprland" "hyprpaper" "hyprlock" "wofi" "waybar" "ntfs-3g" "tree" "discord" "lazygit" "ufw" "zsh" "unzip" "wget" "stow" "curl" "yazi" "neovim" "eza" "btop" "gamemode" "steam" "mangohud" "zoxide" "fzf" "bat" "kitty" "geany" "geany-plugins" "tmux" "jdk23-openjdk" "docker" "ripgrep" "cargo" "fd" "sddm" "starship" "okular" "vlc" "xclip" "isoimagewriter" "hypridle" "pinta" "bluez" "bluez-utils" "networkmanager" "brightnessctl" "wine" "thunderbird" "nwg-look" "thunar" "bluetui")

  for package in "${packages[@]}"; do
	sudo pacman -S "$package" --noconfirm || { echo "Failed to install $package"; }
  done
}

config_ufw() {
  sudo systemctl start ufw
  sudo ufw default deny incoming
  sudo ufw default allow outgoing
  sudo ufw enable
}

copy_config() {
  cp "$HOME/hyprland/.zshrc" "$HOME/"
  cp -r "$HOME/hyprland/.config" "$HOME/"
  cp -r "$HOME/hyprland/Pictures/Wallpaper/" "$HOME/Pictures/"
  sudo cp -r "$HOME/hyprland/sddm/catppuccin-mocha/" "/usr/share/sddm/themes/"
  sudo cp "$HOME/hyprland/sddm/sddm.conf" "/etc/"
  cp "$HOME/hyprland/nwg-look/gsettings" "$HOME/.local/share/nwg-look/"
  read -r -p "Are you using a Laptop? (y/n)" laptop
  if [[ $laptop == "y" ]]; then
    cp "$HOME/hyprland/scripts/battery.sh" "$HOME/.config/hypr/"
  fi
}

install_yay(){
  sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
}

install_nitch() {
	echo "Installing nitch..."
	wget https://raw.githubusercontent.com/unxsh/nitch/main/setup.sh && sh setup.sh
	echo "Finished!"
}

configure_git() {
  read -r -p "Want to configure git? (y/n): " gitconfig
  if [[ $gitconfig == "y" ]]; then
    read -r -p "What is your GitHub username? " username
    git config --global user.name "$username"
    read -r -p "What is your email address? " useremail
    git config --global user.email "$useremail"
    git config --global pull.rebase true
  fi
  
  read -r -p "Want to create ssh key? (y/n): " ssh
  if [[ $ssh == "y" ]]; then
    ssh-keygen -t ed25519 -C "$useremail"
  fi
}


install_themes() {
  sudo cp "$HOME/hyprland/Fonts/MesloLGS NF Regular.ttf" "/usr/share/fonts"
  sudo cp -r "$HOME/hyprland/Cursor/Bibata-Modern-Ice" "/usr/share/icons"
  
  echo "Installing Vencord..."

  bash "$HOME/hyprland/Vencord/VencordInstaller.sh"

  cp -r "$HOME/hyprland/Vencord/themes/" "$HOME/.config/Vencord/"

  echo "Done!"

}

add_tmux_tpm() {
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  mkdir -p ~/.config/tmux/plugins/catppuccin 
  git clone -b v2.1.2 https://github.com/catppuccin/tmux.git ~/.config/tmux/plugins/catppuccin/tmux
}

install_packages
configure_git

config_ufw
install_nitch

if [[ ! -d "$HOME/Pictures/Screenshots/" ]]; then 
  mkdir -p "$HOME/Pictures/Screenshots/"
fi

if [[ ! -d "$HOME/.local/share/nwg-look/" ]]; then 
  mkdir -p "$HOME/.local/share/nwg-look/"
fi

copy_config
install_themes
add_tmux_tpm

echo "Creating work directory"
mkdir -p "$HOME/Documents/Github/Projects"
echo "Done"
    
install_yay

echo "Installing packages from yay"
yay -S --noconfirm $(cat "$HOME/hyprland/yay-packages.txt")
echo "Finished!"

cat "$HOME/.ssh/id_ed25519.pub"

chsh -s /bin/zsh 

systemctl enable sddm 

echo "Installing nvm..."
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash

sudo cp "$HOME/hyprland/scripts/updateos" "/usr/bin/"

echo "Now you are ready to reboot"
